#+TITLE: 06-364 Chemical Reaction Engineering					Spring 2017 - 9 units 
	
Engineering Topics: 100%, with 25% Design
100% Lecture, 0% Recitation, 0% Laboratory

Instructor: John Kitchin                           Program: Chemical Engineering

Web-site: http://bit.ly/s17-06364 

We will use Slack: http://s17-06-364.slack.com and email for class communications.

Required Text(s): Elements of Chemical Reaction Engineering H.S. Fogler 
Specific Course Information: Fundamental concepts in the kinetic modeling of chemical reactions, the treatment and analysis of rate data. Multiple reactions and reaction mechanisms. Analysis and design of ideal and non-ideal reactor systems. Energy effects and mass transfer in reactor systems. Introductory principles in heterogeneous catalysis.

Prerequisites: 06-321, 06-323, 09-347   Required: Yes

* Specific Course Goals
After this course you will be able to:

- D1 Formulate and solve mass balance equations for systems with reactions	a
- D2 Choose a reactor and determine its size for a given application	c,e/C
- D3 Design reactors with changing molar flow rates and pressure drops 	c,e/C
- D4 Analyze kinetic data to obtain rate laws and kinetic parameters	a,b,k/D
- D5 Develop a mechanism that is consistent with an experimental rate law	b
- D6 Design reactors that maximize selectivity and/or yield of products	c,e
- D7 Design and analyze non-isothermal reactors	a/C
- D8 Use mathematical software in the design of reactors and analysis of data	k/C


Topics: 
-	Conversion and reactor sizing
-	Rate laws and stoichiometry
-	Isothermal reactor design
-	Collection and analysis of rate data
-	Multiple reactions and selectivity
-	Non-elementary reaction kinetics
-	Non-isothermal reactor design
-	Unsteady operation of reactors
-	Catalysis and catalytic reactors

* Grading

#+caption: Categories and weights for graded
#+tblname: categories
| Category      | weight |
|---------------+--------|
| homework      |   0.15 |
| exam1         |    0.2 |
| exam2         |    0.3 |
| Final exam    |   0.35 |

Homeworks will be assigned one to three times a week. Each assignment will typically be one problem that should take 30-90 minutes to complete.

Quizzes will be given in class. You should be prepared to take a quiz at any time. These will typically be short, timed problems.

Exams will probably be scheduled and given during class. 

I recommend you bring your computer to class every day. You will need it to follow the lecture notes.

Late assignments will automatically lose 50% of their points. Late assignments can only be turned in by email.

** Grading criteria

You are transitioning into a young professional at this point. That means assignments are done professionally too. In addition to the technical correctness of your work, we will also be assessing the professionalism with which it is presented. Each assignment will show the rubric it will be graded with at the top of the file.

There will be a straight scale (no curve) so you will always know exactly what your grade is at all times. Each problem will be graded considering the approach used, the correctness of the answer, the neatness and quality of presentation, etc... Each category of the rubric will be given a letter grade that indicates your level of performance in that category.

"A" work has the following characteristics: The correct approach is used and the problem is set up correctly. The work is not over-simplified and it is easy to see it is done correctly. Any assumptions made were stated and justified. The answers are correct or only the most trivial errors are present, and were identified by the student. All of the correct units were used. The presentation is complete, clear, logical, neat and in order. Error analysis was performed if appropriate. Any figures used have properly labeled axes with units, and a legend if there is more than one curve. Essentially everything that should have been done was done and done correctly. This is the kind of work an employer wants their employees to do, and the kind of work you will be promoted for doing. You should be proud of this work.

"B" work is deficient in one or more of the properties of "A" work. It might be basically right, but essential details are missing such as units, or the presentation is sloppy. You will get by with this kind of work, but you should not expect to be praised for it.

"C" quality work is deficient in more than two of the properties of "A" work. You would probably not get fired for this kind of work, but you may be notified you need to improve and you should not expect any kind of promotion. This is the bare minimum of expected performance.

"D" work is not considered acceptable performance. Repeat offenses could lead to the loss of your job.

"R" work is totally unacceptable performance. You will be fired.

plus/minus modifiers will be used to provide finer grained grades.

Each problem will have a point value associated with it. The letter grade you get serves as a multiplier on that point value. The multipliers are:

| Lettergrade | multiplier |
|-------------+------------|
| A++         |          1 |
| A+          |       0.95 |
| A           |        0.9 |
| A-          |       0.85 |
| A/B         |        0.8 |
| B+          |       0.75 |
| B           |        0.7 |
| B-          |       0.65 |
| B/C         |        0.6 |
| C+          |       0.55 |
| C           |        0.5 |
| C-          |       0.45 |
| C/D         |        0.4 |
| D+          |       0.35 |
| D           |        0.3 |
| D-          |       0.25 |
| D/R         |        0.2 |
| R+          |       0.15 |
| R           |        0.1 |
| R-          |       0.05 |
| R- -        |        0.0 |

At the end of the semester I will calculate what fraction of the possible points you have earned, and your grade will be based on this distribution:

| 80% >= grade         | A |
| 60% >= grade < 80    | B |
| 40% >= grade < 60    | C |
| 20% >= grade < 40    | D |
| grade < 20%          | R |

Note that the standard grade for correct work is an "A", which is not equal to "100%". It is worth 90%, which is well above the cutoff for an A. The A+ and A++ designations are reserved for work that is well above "correct".

* Academic honesty

All work is expected to be your original work. You may work with class members to solve the homework problems, but you must turn in your own solutions. It is cheating to turn in someone else's work as your own. If you use code from the internet or the course notes, you should note this in your solution. Duplicated assignments (e.g. two students who turn in the same work) will receive zeros and a warning. Repeat offenses will be reported as academic dishonesty.

When in doubt, review this website: http://www.cmu.edu/academic-integrity/, and ask if anything is unclear /before/ you get in trouble. In particular see these sites:
  - http://www.cmu.edu/academic-integrity/collaboration/index.html
  - http://www.cmu.edu/academic-integrity/cheating/index.html
  - http://www.cmu.edu/academic-integrity/plagiarism/index.html

* Religious holidays

We will accommodate religious holidays when possible. If your work will be affected by a religious holiday, you must inform Professor Kitchin as early as possible to work out an accommodation in advance.

* Take care of yourself and each other

Do your best to maintain a healthy lifestyle this semester by eating well, exercising, avoiding drugs and alcohol, getting enough sleep and taking some time to relax. This will help you achieve your goals and cope with stress.

All of us benefit from support during times of struggle. You are not alone. There are many helpful resources available on campus and an important part of the college experience is learning how to ask for help. Asking for support sooner rather than later is often helpful.

If you or anyone you know experiences any academic stress, difficult life events, or feelings like anxiety or depression, we strongly encourage you to seek support. Counseling and Psychological Services (CaPS) is here to help: call 412-268-2922 and visit their website at http://www.cmu.edu/counseling/. Consider reaching out to a friend, faculty or family member you trust for help getting connected to the support that can help.

If you or someone you know is feeling suicidal or in danger of self-harm, call someone immediately, day or night:

CaPS: 412-268-2922

Re:solve Crisis Network: 888-796-8226

If the situation is life threatening, call the police:

           On campus: CMU Police: 412-268-2323

           Off campus: 911

If you have questions about this or your coursework, please let me know.
